package com.dewarder.akommons.content

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.support.v4.content.ContextCompat
import com.dewarder.akommons.os.isPreLollipop

fun Context.isPermissionsGranted(vararg permissions: Permission): Boolean =
    isPreLollipop() || permissions.all { permission ->
        ContextCompat.checkSelfPermission(this, permission.value) == PackageManager.PERMISSION_GRANTED
    }

fun Context.isPermissionsGranted(vararg permissions: String): Boolean =
    isPreLollipop() || permissions.all { rawPermission ->
        ContextCompat.checkSelfPermission(this, rawPermission) == PackageManager.PERMISSION_GRANTED
    }

enum class Permission(val value: String) {
    ACCESS_COARSE_LOCATION(Manifest.permission.ACCESS_COARSE_LOCATION),
    ACCESS_LOCATION_EXTRA_COMMANDS(Manifest.permission.ACCESS_LOCATION_EXTRA_COMMANDS),
    ACCESS_NETWORK_STATE(Manifest.permission.ACCESS_NETWORK_STATE),
    ACCESS_NOTIFICATION_POLICY(Manifest.permission.ACCESS_NOTIFICATION_POLICY),
    ACCESS_WIFI_STATE(Manifest.permission.ACCESS_WIFI_STATE),
    ACCESS_FINE_LOCATION(Manifest.permission.ACCESS_FINE_LOCATION),
    ACCOUNT_MANAGER(Manifest.permission.ACCOUNT_MANAGER),
    ADD_VOICEMAIL(Manifest.permission.ADD_VOICEMAIL),
    BATTERY_STATS(Manifest.permission.BATTERY_STATS),
    BIND_ACCESSIBILITY_SERVICE(Manifest.permission.BIND_ACCESSIBILITY_SERVICE),
    BIND_APPWIDGET(Manifest.permission.BIND_APPWIDGET),
    BIND_CARRIER_SERVICES(Manifest.permission.BIND_CARRIER_SERVICES),
    BIND_CHOOSER_TARGET_SERVICE(Manifest.permission.BIND_CHOOSER_TARGET_SERVICE),
    BIND_CONDITION_PROVIDER_SERVICE(Manifest.permission.BIND_CONDITION_PROVIDER_SERVICE),
    BIND_DEVICE_ADMIN(Manifest.permission.BIND_DEVICE_ADMIN),
    BIND_DREAM_SERVICE(Manifest.permission.BIND_DREAM_SERVICE),
    BIND_INCALL_SERVICE(Manifest.permission.BIND_INCALL_SERVICE),
    BIND_INPUT_METHOD(Manifest.permission.BIND_INPUT_METHOD),
    BIND_MIDI_DEVICE_SERVICE(Manifest.permission.BIND_MIDI_DEVICE_SERVICE),
    BIND_NFC_SERVICE(Manifest.permission.BIND_NFC_SERVICE),
    BIND_NOTIFICATION_LISTENER_SERVICE(Manifest.permission.BIND_NOTIFICATION_LISTENER_SERVICE),
    BIND_PRINT_SERVICE(Manifest.permission.BIND_PRINT_SERVICE),
    BIND_QUICK_SETTINGS_TILE(Manifest.permission.BIND_QUICK_SETTINGS_TILE),
    BIND_REMOTEVIEWS(Manifest.permission.BIND_REMOTEVIEWS),
    BIND_SCREENING_SERVICE(Manifest.permission.BIND_SCREENING_SERVICE),
    BIND_TELECOM_CONNECTION_SERVICE(Manifest.permission.BIND_TELECOM_CONNECTION_SERVICE),
    BIND_TEXT_SERVICE(Manifest.permission.BIND_TEXT_SERVICE),
    BIND_TV_INPUT(Manifest.permission.BIND_TV_INPUT),
    BIND_VOICE_INTERACTION(Manifest.permission.BIND_VOICE_INTERACTION),
    BIND_VPN_SERVICE(Manifest.permission.BIND_VPN_SERVICE),
    BIND_VR_LISTENER_SERVICE(Manifest.permission.BIND_VR_LISTENER_SERVICE),
    BIND_WALLPAPER(Manifest.permission.BIND_WALLPAPER),
    BLUETOOTH(Manifest.permission.BLUETOOTH),
    BLUETOOTH_ADMIN(Manifest.permission.BLUETOOTH_ADMIN),
    BLUETOOTH_PRIVILEGED(Manifest.permission.BLUETOOTH_PRIVILEGED),
    BODY_SENSORS(Manifest.permission.BODY_SENSORS),
    BROADCAST_PACKAGE_REMOVED(Manifest.permission.BROADCAST_PACKAGE_REMOVED),
    BROADCAST_SMS(Manifest.permission.BROADCAST_SMS),
    BROADCAST_STICKY(Manifest.permission.BROADCAST_STICKY),
    BROADCAST_WAP_PUSH(Manifest.permission.BROADCAST_WAP_PUSH),
    CALL_PHONE(Manifest.permission.CALL_PHONE),
    CALL_PRIVILEGED(Manifest.permission.CALL_PRIVILEGED),
    CAMERA(Manifest.permission.CAMERA),
    CAPTURE_AUDIO_OUTPUT(Manifest.permission.CAPTURE_AUDIO_OUTPUT),
    CAPTURE_SECURE_VIDEO_OUTPUT(Manifest.permission.CAPTURE_SECURE_VIDEO_OUTPUT),
    CAPTURE_VIDEO_OUTPUT(Manifest.permission.CAPTURE_VIDEO_OUTPUT),
    CHANGE_COMPONENT_ENABLED_STATE(Manifest.permission.CHANGE_COMPONENT_ENABLED_STATE),
    CHANGE_CONFIGURATION(Manifest.permission.CHANGE_CONFIGURATION),
    CHANGE_NETWORK_STATE(Manifest.permission.CHANGE_NETWORK_STATE),
    CHANGE_WIFI_MULTICAST_STATE(Manifest.permission.CHANGE_WIFI_MULTICAST_STATE),
    CHANGE_WIFI_STATE(Manifest.permission.CHANGE_WIFI_STATE),
    CLEAR_APP_CACHE(Manifest.permission.CLEAR_APP_CACHE),
    CONTROL_LOCATION_UPDATES(Manifest.permission.CONTROL_LOCATION_UPDATES),
    DELETE_CACHE_FILES(Manifest.permission.DELETE_CACHE_FILES),
    DELETE_PACKAGES(Manifest.permission.DELETE_PACKAGES),
    DIAGNOSTIC(Manifest.permission.DIAGNOSTIC),
    DISABLE_KEYGUARD(Manifest.permission.DISABLE_KEYGUARD),
    DUMP(Manifest.permission.DUMP),
    EXPAND_STATUS_BAR(Manifest.permission.EXPAND_STATUS_BAR),
    FACTORY_TEST(Manifest.permission.FACTORY_TEST),
    GET_ACCOUNTS(Manifest.permission.GET_ACCOUNTS),
    GET_ACCOUNTS_PRIVILEGED(Manifest.permission.GET_ACCOUNTS_PRIVILEGED),
    GET_PACKAGE_SIZE(Manifest.permission.GET_PACKAGE_SIZE),
    GLOBAL_SEARCH(Manifest.permission.GLOBAL_SEARCH),
    INSTALL_LOCATION_PROVIDER(Manifest.permission.INSTALL_LOCATION_PROVIDER),
    INSTALL_PACKAGES(Manifest.permission.INSTALL_PACKAGES),
    INSTALL_SHORTCUT(Manifest.permission.INSTALL_SHORTCUT),
    INTERNET(Manifest.permission.INTERNET),
    KILL_BACKGROUND_PROCESSES(Manifest.permission.KILL_BACKGROUND_PROCESSES),
    LOCATION_HARDWARE(Manifest.permission.LOCATION_HARDWARE),
    MANAGE_DOCUMENTS(Manifest.permission.MANAGE_DOCUMENTS),
    MASTER_CLEAR(Manifest.permission.MASTER_CLEAR),
    MEDIA_CONTENT_CONTROL(Manifest.permission.MEDIA_CONTENT_CONTROL),
    MODIFY_AUDIO_SETTINGS(Manifest.permission.MODIFY_AUDIO_SETTINGS),
    MODIFY_PHONE_STATE(Manifest.permission.MODIFY_PHONE_STATE),
    MOUNT_FORMAT_FILESYSTEMS(Manifest.permission.MOUNT_FORMAT_FILESYSTEMS),
    MOUNT_UNMOUNT_FILESYSTEMS(Manifest.permission.MOUNT_UNMOUNT_FILESYSTEMS),
    NFC(Manifest.permission.NFC),
    PACKAGE_USAGE_STATS(Manifest.permission.PACKAGE_USAGE_STATS),
    PROCESS_OUTGOING_CALLS(Manifest.permission.PROCESS_OUTGOING_CALLS),
    READ_CALENDAR(Manifest.permission.READ_CALENDAR),
    READ_CALL_LOG(Manifest.permission.READ_CALL_LOG),
    READ_CONTACTS(Manifest.permission.READ_CONTACTS),
    READ_EXTERNAL_STORAGE(Manifest.permission.READ_EXTERNAL_STORAGE),
    READ_FRAME_BUFFER(Manifest.permission.READ_FRAME_BUFFER),
    READ_LOGS(Manifest.permission.READ_LOGS),
    READ_PHONE_STATE(Manifest.permission.READ_PHONE_STATE),
    READ_SMS(Manifest.permission.READ_SMS),
    READ_SYNC_SETTINGS(Manifest.permission.READ_SYNC_SETTINGS),
    READ_SYNC_STATS(Manifest.permission.READ_SYNC_STATS),
    READ_VOICEMAIL(Manifest.permission.READ_VOICEMAIL),
    REBOOT(Manifest.permission.REBOOT),
    RECEIVE_BOOT_COMPLETED(Manifest.permission.RECEIVE_BOOT_COMPLETED),
    RECEIVE_MMS(Manifest.permission.RECEIVE_MMS),
    RECEIVE_SMS(Manifest.permission.RECEIVE_SMS),
    RECEIVE_WAP_PUSH(Manifest.permission.RECEIVE_WAP_PUSH),
    RECORD_AUDIO(Manifest.permission.RECORD_AUDIO),
    REORDER_TASKS(Manifest.permission.REORDER_TASKS),
    REQUEST_IGNORE_BATTERY_OPTIMIZATIONS(Manifest.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS),
    REQUEST_INSTALL_PACKAGES(Manifest.permission.REQUEST_INSTALL_PACKAGES),
    SEND_RESPOND_VIA_MESSAGE(Manifest.permission.SEND_RESPOND_VIA_MESSAGE),
    SEND_SMS(Manifest.permission.SEND_SMS),
    SET_ALARM(Manifest.permission.SET_ALARM),
    SET_ALWAYS_FINISH(Manifest.permission.SET_ALWAYS_FINISH),
    SET_ANIMATION_SCALE(Manifest.permission.SET_ANIMATION_SCALE),
    SET_DEBUG_APP(Manifest.permission.SET_DEBUG_APP),
    SET_PROCESS_LIMIT(Manifest.permission.SET_PROCESS_LIMIT),
    SET_TIME(Manifest.permission.SET_TIME),
    SET_TIME_ZONE(Manifest.permission.SET_TIME_ZONE),
    SET_WALLPAPER(Manifest.permission.SET_WALLPAPER),
    SET_WALLPAPER_HINTS(Manifest.permission.SET_WALLPAPER_HINTS),
    SIGNAL_PERSISTENT_PROCESS(Manifest.permission.SIGNAL_PERSISTENT_PROCESSES),
    STATUS_BAR(Manifest.permission.STATUS_BAR),
    SYSTEM_ALERT_WINDOW(Manifest.permission.SYSTEM_ALERT_WINDOW),
    TRANSMIT_IR(Manifest.permission.TRANSMIT_IR),
    UNINSTALL_SHORTCUT(Manifest.permission.UNINSTALL_SHORTCUT),
    UPDATE_DEVICE_STATS(Manifest.permission.UPDATE_DEVICE_STATS),
    USE_FINGERPRINT(Manifest.permission.USE_FINGERPRINT),
    USE_SIP(Manifest.permission.USE_SIP),
    VIBRATE(Manifest.permission.VIBRATE),
    WAKE_LOCK(Manifest.permission.WAKE_LOCK),
    WRITE_APN_SETTINGS(Manifest.permission.WRITE_APN_SETTINGS),
    WRITE_CALENDAR(Manifest.permission.WRITE_CALENDAR),
    WRITE_CALL_LOG(Manifest.permission.WRITE_CALL_LOG),
    WRITE_CONTACTS(Manifest.permission.WRITE_CONTACTS),
    WRITE_EXTERNAL_STORAGE(Manifest.permission.WRITE_EXTERNAL_STORAGE),
    WRITE_GSERVICES(Manifest.permission.WRITE_GSERVICES),
    WRITE_SECURE_SETTINGS(Manifest.permission.WRITE_SECURE_SETTINGS),
    WRITE_SETTINGS(Manifest.permission.WRITE_SETTINGS),
    WRITE_SYNC_SETTINGS(Manifest.permission.WRITE_SYNC_SETTINGS),
    WRITE_VOICEMAIL(Manifest.permission.WRITE_VOICEMAIL)
}